### ISSUE TITLE
Error on kodi 18

### ISSUE THREAD

**Issue by powerfrontier** [5-star/plugin.video.last_played#26]
Not working with Raspberry Pi 2 and kodi 18.7. Addon version is 6.1.0. Here is the error:

`2022-06-29 17:38:25.471 T:1599025344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'translatePath'
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.last_played/default.py", line 23, in <module>
                                                txtpath = xbmcvfs.translatePath(addon.getAddonInfo('profile'))
                                            AttributeError: 'module' object has no attribute 'translatePath'
                                            -->End of Python script error report<--
`

**Comment by powerfrontier** [comment]
The only way I found to work is downgrading to plugin.video.last_played-1.3.1.zip  from https://github.com/5-star/repository.5star/tree/master/zips/plugin.video.last_played repo. So I guess the new versions of the plugin (6 and forward) are not backward compatible on kodi. Is it right?

**Comment by 5-star** [comment]
Kodi migrated to python3 which broke a lot of things.

I tried to keep it backward compatible but i cant test all versions and devices.

Your solution is the best, using a previous version.
